# IBM Developer's Workframe/2 Make File Creation run at 15:55:23 on 01/17/94

# Make File Creation run in directory:
#   F:\FRACTZ;

# Assumed INCLUDE environment variable path:
#   F:\FRACTZ;
#   F:\IBMCPP\INCLUDE;
#   F:\IBMCPP\IBMCLASS;
#   F:\TOOLKT21\CPLUS\OS2H;
#   F:\TOOLKT21\C\OS2H;
#   F:\TOOLKT21\C\OS2H\VDD;
#   F:\TOOLKT21\ASM\OS2INC;


INCLUDE002=.
INCLUDE002=$(INCLUDE002);$(INCLUDE)

INCLUDE001=.
INCLUDE001=$(INCLUDE001);$(INCLUDE)

INCLUDE000=$(INCLUDE)


FRACTZ.RES:  FRACTZ.RC  \
#  {$(INCLUDE002)}OS2.H  \
   {$(INCLUDE002)}FRACTZ.H  \
   FRACTZ.ICO  \
   FRACTZ.DLG  \
     FRACTZ.H  \
   MAKEFILE

fractz.OBJ:  fractz.cpp  \
#  {$(INCLUDE000)}os2.h  \
#  {$(INCLUDE000)}stdlib.h  \
#  {$(INCLUDE000)}stdio.h  \
#  {$(INCLUDE000)}string.h  \
#  {$(INCLUDE000)}complex.h  \
   {$(INCLUDE001)}fractz.h  \
   MAKEFILE
